### ISSUE TITLE
impossible to change the resolution from 512x512

### ISSUE THREAD

**Issue by AugmentedRealityCat** [Trentonom0r3/After-Diffusion#5]
**Describe the bug**
According to the youtube demonstration, the composition's resolution should be determining the resolution of the generated image, but it always generates 512x512 images. I tried to change the resolution of the solid, but this does not seem to have any effect either on the resolution.

How can I document this bug better for you ? I activated AE's log file, but that doesn't look like the kind of problem that would show up there. Stable Diffusion's window is saying this when ControlNet is activated in a 1024x1024 composition from a 1024x1024 solid:

target_H = 512
target_W = 512

I also tried a 1024x512 just in case, but that also gives me a 512x512 image.

and one more thing: THIS IS AMAZING ! Thank you so much for making and sharing this.

**Comment by Trentonom0r3** [comment]
First off, thank you very much!!

Are you using the ZXP method, or the CEP method?
TXT2IMG or IMG2IMG?

I forgot that I added code that takes care of the controlnet input image, and apparently it is actually working.

 I ran a few tests, and from what I can gather, the original 512x512 selection is being sent instead of your new solid size, so there is some sort of issue with either the selection, or the memory cache itself. 

Another possibility is if you are running TXT2IMG.
If you're running TXT2IMG, and using a control Image, since TXT2IMG isn't adjusted on the comp size yet, the image will always output to 512x512. Otherwise, if you run IMG2IMG it should run fine.

These are my IMG2IMG steps, if the issue you're having is with that.

1. Start with a fresh open of AE.
2. Import your footage, and save a new project. (Make a new folder to hold the project, just for simplicity's sake.)
3. Open the Extension, and refresh your models. 
4. Adjust your settings, enable controlnet, etc;
5. CTRL + Y, create solid.
6. (may not be necessary, but for debugging purposes) click on the viewer, then click back into the extension.
7. Click Generate, and watch your webUI.

When I followed these steps, the image was generated at the proper 1024x1024 size;
raw_H = 1024
raw_W = 1024
target_H = 1024
target_W = 1024
estimation = 1024.0
preprocessor resolution = 1024

When I ran it using TXT2IMG and a control IMG, I received this;
raw_H = 1024
raw_W = 1024
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512

**Comment by AugmentedRealityCat** [comment]
> Are you using the ZXP method, or the CEP method? TXT2IMG or IMG2IMG?

I used ZXP. I first tried CEP but I was dumb and forgot to set the permissions accordingly in the AE preferences panel, hence why it did not work I suppose. So I installed ZXP. I can give the CEP method a try again if you want.

I'm going to try the new v1.1 version in 10 minutes or so and come back to tell you if the resolution problem has been solved.

**Comment by AugmentedRealityCat** [comment]
Looks like the resolution problem has been solved !

If I use txt2img in a 1024x1024 composition, starting from a 1024x512 solid layer, I get a 1024x1024 image result, which is the expected behaviour. 

If I include ControlNet and follow the complete procedure (steps 1-7 from your reply above this one) here is what I get in the CLI window:

```
ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
Loading preprocessor: canny
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 1024
target_W = 1024
estimation = 1024.0
preprocessor resolution = 1024
```

For some reasons I do have other problems with IMG2IMG and with the Extra panel (that simply won't open). I'll document these different issues in separate posts.

**Comment by Trentonom0r3** [comment]
Sounds good! CEP or ZXP--- either one will work the same now! Looking forward to hearing the result!

**Comment by AugmentedRealityCat** [comment]
Just for reference, I used ZXP again after downloading v1.1 as a zip (after selecting that branch on your code's page).
I guess I should be closing the issue now ? 

Thanks a lot for your amazing tech support ! You could give Adobe a few lessons on the matter.

**Comment by Trentonom0r3** [comment]
> 

I'll go ahead and mark this issue as closed then. Couple of notes.
on TXT2IMG, you actually don't need to use a solid, that's just for IMG2IMG, and really only if you're looking to work on a specific part of the main image. 
raw_h and raw_w are based on the image you use for the control image, or if you are running img2img it should also be based on the comp size, so long as you aren't using an input(control) image of a different size. 
target_h and target_w are based on the selected comp size. Its a good practice to always click onto the viewer (assuming the comp/pre-comp you're wanting to run generation on is open.) before you click on generate.
In regards to the extras tab-- it actually doesn't have anything in it, so it'll appear as if it isn't working.

**Comment by AugmentedRealityCat** [comment]
> In regards to the extras tab-- it actually doesn't have anything in it, so it'll appear as if it isn't working.

Ok good to know ! I won't report that as a bug then. Thanks for all the info.

**Comment by Trentonom0r3** [comment]
> 

Also, In this section-- Were you running TXT2IMG or IMG2IMG, and did you put anything into the control image slot?

**Comment by AugmentedRealityCat** [comment]
I was running TXT2IMG because I had problems with IMG2IMG and I wanted to make sure I was doing everything right before reporting what I was experiencing. Basically, it produced videos instead of still pictures, but I now understand it's because I had not set the work area to one frame - I did and now it works. One more problem solved !

And yes, I did test with and image in the ControlNet slot.

**Comment by Trentonom0r3** [comment]
> I was running TXT2IMG because I had problems with IMG2IMG and I wanted to make sure I was doing everything right before reporting what I was experiencing. Basically, it produced videos instead of still pictures, but I now understand it's because I had not set the work area to one frame - I did and now it works. One more problem solved !
> 
> 
> 
> And yes, I did test with and image in the ControlNet slot.
> 
> EDIT: and that image was in 512x512

Ahhh, yeah, I think that the 'video instead of still' you're referring to is actually just a still frame that is the work area length. I need to change that to import as a single frame at comp frame rate like it does with other functions. 

That makes sense now! I also need to add a way to remove the control image, other than by closing and reopening the extension.
